---
title: "Untitled"
author: "Kaylah Marcello"
date: '2023-01-17'
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("viridisLite")
#install.packages("svglite")
#install.packages("factoextra")
#install.packages("cluster")
#install.packages("ggdendro")
#install.packages("grid")
```



## Load the Libraries

```{r}
library(tidyverse)
library(RColorBrewer)
library(paletteer)
library(janitor)
library(here)
library(skimr)
library(viridis)
library(shiny)
library(shinydashboard)
library(devtools)
library(svglite)
#library(cluster)
#library(factoextra)
library(ggdendro)
library(grid)
```

```{r}
filament_cyanos <- readr::read_csv("data/filamentous_cyano_meta.csv")
```
## Get an Idea of the Structure
```{r}
summary(filament_cyanos)
```

```{r}
head(filament_cyanos)
```

```{r}
filament_cyanos <- clean_names(filament_cyanos)
```

```{r}
names(filament_cyanos)
```

```{r}
head(filament_cyanos)
```


## Cold Tolerance Gene Counts by Genus and Specific Strain

```{r}
gene_data_genus <- filament_cyanos %>% 
  select(genus, contains("gene_")) %>% 
  pivot_longer(-genus,
               names_to = "gene",
               values_to = "gene_count") %>% 
  filter(!is.na(gene_count))

gene_data_genus
```

```{r}
gene_data_genus$gene_count <- as.factor(gene_data_genus$gene_count)
```


```{r}
fil_heatmap <- gene_data_genus %>%
  ggplot(aes(y=gene, x=genus))+
  geom_tile(aes(fill= gene_count))+
  scale_fill_viridis(discrete=TRUE, direction = -1, option = "mako")+
  theme(legend.position = "right",
        text = element_text(size=6),
        axis.text.x = element_text(angle = 45, hjust=1))+
  coord_fixed()+ #maintains aspect ratio so 1 unit on x is 1 unit on y
  labs(title = "Cold Tolerance Gene Count for Cyanobacteria Genera",x = "Genus", y = "Gene")

ggsave("figures/fil_gene_count_genus_heatmap.svg", width=10, height=6, plot = fil_heatmap, dpi = 200)

fil_heatmap 
```


```{r}
gene_data_organism <- filament_cyanos %>% 
  select(organism, contains("gene_")) %>% # get rid of the gene_ part for the final pres.
  pivot_longer(-organism,
               names_to = "gene",
               values_to = "gene_count") %>% 
  filter(!is.na(gene_count))
gene_data_organism
```

## combining heatmap and dendrogram

```{r}
gene_data_organism$gene_count <- as.numeric(gene_data_organism$gene_count) # needs to be numeric for scale()
lapply(gene_data_organism, class)
```

```{r}
clust_map_org <- gene_data_organism %>% # make pivot_wider for scale()
  pivot_wider(names_from = "gene",
              values_from = "gene_count")
clust_map_org
```

[Clusters and Heatmaps: Jeff Oliver](https://jcoliver.github.io/learn-r/008-ggplot-dendrograms-and-heatmaps.html)

```{r}
#clust_map_org <- scale(clust_map_org)
#clust_map_org %>% 
  #mutate(across(where(is.numeric, scale))

# this is where I got the info
# https://jcoliver.github.io/learn-r/008-ggplot-dendrograms-and-heatmaps.html
scaled_clust_map <- clust_map_org 
scaled_clust_map[, c(2:22)] <- scale(scaled_clust_map[, 2:22])
scaled_clust_map
```

```{r}
scaled_matrix <- as.matrix(scaled_clust_map[, c(2:22)])
rownames(scaled_matrix) <- scaled_clust_map$organism
organisms_dendro <- as.dendrogram(hclust(d = dist(x = scaled_matrix)))
```

```{r}
dendro_plot <- ggdendrogram(data = organisms_dendro, rotate = TRUE)
dendro_plot
```

```{r}
dendro_plot <- dendro_plot + 
  theme(axis.text.y = element_text(size = 0),
        legend.text = element_text(size = 0))
dendro_plot
```

```{r}
gene_data_organism$gene_count <- as.factor(gene_data_organism$gene_count)
lapply(gene_data_organism, class)
```

```{r}
fil_heatmap <- gene_data_organism %>%
  ggplot(aes(y=gene, x=organism))+
  geom_tile(aes(fill= gene_count))+
  scale_fill_viridis(discrete=TRUE, direction = -1, option = "mako")+
  theme(legend.position = "bottom",
        legend.justification = "left",
        legend.key.size = unit(0.2, "cm"),
        text = element_text(size=6),
        axis.text.x = element_text(angle = 60, hjust=1))+
  coord_flip()+ #maintains aspect ratio so 1 unit on x is 1 unit on y
  labs(title = "Cold Tolerance Gene Count for Cyanobacteria Strains",x = "Cyanobacteria", y = "Gene")

ggsave("figures/fil_gene_count_heatmap.png", width=10, height=6, plot = fil_heatmap, dpi = 200)

fil_heatmap
```

```{r}
grid.newpage()
print(fil_heatmap,
      vp = viewport(x = 0.4, y = 0.5, width = 0.8, height = 1.0))
print(dendro_plot,
      vp = viewport(x = 0.9, y = 0.58, width = 0.2, height = 0.81))
```








## Cyanobacteria Strain Environmental Temperatures

```{r}
temperature_gene <- filament_cyanos %>% 
  select(organism, tempurature_avg, contains("gene_")) %>% 
  filter(!is.na(tempurature_avg))
temperature_gene
```

```{r}
temp_organism <- filament_cyanos %>% 
  select(organism, tempurature_avg, genus) %>% 
  filter(!is.na(tempurature_avg)) %>% 
  ggplot(aes(x = organism, y = tempurature_avg, fill = genus)) +
  geom_col()+
  scale_fill_viridis(discrete=TRUE, option = "mako")+
  theme(legend.position = "right",
        text = element_text(size=10),
        axis.text.x = element_text(angle = 60, hjust=1))+
  labs(title = "Environmental Temperature for Cyanobacteria Species",x = "Cyanobacteria", y = "Temperature C")
temp_organism
ggsave("figures/temp_organism_plot.png", width=10, height=6, plot = temp_organism, dpi = 200)


```

## Compare single gene count to temperature in previouse figure

```{r}
temp_organism <- filament_cyanos %>% 
  select(organism, tempurature_avg, genus, gene_des_a) %>% 
  filter(!is.na(tempurature_avg)) %>% 
  filter(!is.na(gene_des_a)) %>% 
  ggplot(aes(x = organism, y = gene_des_a, fill = genus)) +
  geom_col()+
  scale_fill_viridis(discrete=TRUE, option = "mako")+
  theme(legend.position = "right",
        text = element_text(size=10),
        axis.text.x = element_text(angle = 60, hjust=1))+
  labs(title = "CTG count for Cyanobacteria Species",x = "Cyanobacteria", y = "DesA Gene Count")

ggsave("figures/fil_gene_plot.png", width=10, height=6, plot = temp_organism, dpi = 200)

temp_organism
```